"""Regenerate the Smart Academic Repository / Student Outcome test samples
under test-files/repository-samples/.

Two kinds of content here, deliberately different in provenance:

- research-papers/ and journal-articles/ are REAL PDFs downloaded from arXiv,
  PLOS ONE, and Nature Scientific Reports (open access, freely redistributable)
  -- not regenerated by this script. See repository-samples/README.md for the
  source list. If they're ever missing, re-download them per that README
  rather than trying to synthesize a paper.
- offer-letters/ and ojt-letters/ are realistic, constructed sample documents
  (fictional student, fictional reference numbers) styled after each named
  company's typical offer-letter format, for testing the document
  classifier/student-outcome extractor against company-name and role-style
  detection. Same real-PDF-bytes philosophy as test-files/generate_fixtures.py
  -- these exercise the actual text-extraction path, not a synthetic object.

Run from anywhere:
    backend/.venv/Scripts/python.exe test-files/generate_repository_samples.py
"""

from __future__ import annotations

from pathlib import Path

import pymupdf

ROOT = Path(__file__).parent / "repository-samples"


def write_pdf(path: Path, lines: list[str]) -> None:
    document = pymupdf.open()
    page = document.new_page()
    text = "\n".join(lines)
    page.insert_text((60, 70), text, fontsize=10.5, lineheight=1.35)
    path.parent.mkdir(parents=True, exist_ok=True)
    document.save(path)
    document.close()


STUDENT_NAME = "Rohan Deshmukh"
ROLL_NUMBER = "BE-CMPN-2026-0142"
COLLEGE = "Government College of Engineering, Pune"


def offer_letter(company: str, address: str, role: str, location: str, stipend_or_ctc: str,
                  joining_date: str, manager: str, ref_no: str, duration: str | None = None) -> list[str]:
    lines = [
        company,
        address,
        "",
        f"Ref: {ref_no}",
        "Date: 02 June 2026",
        "",
        f"Dear {STUDENT_NAME},",
        "",
        f"Sub: Offer of {'Internship' if duration else 'Employment'} - {role}",
        "",
        f"We are pleased to offer you the position of {role} with {company},",
        f"based out of our {location} office, following your interview process",
        "and successful completion of all selection rounds.",
        "",
    ]
    if duration:
        lines += [
            f"This is an internship engagement for a duration of {duration},",
            f"commencing on {joining_date}. A stipend of {stipend_or_ctc} per month",
            "will be paid, subject to applicable statutory deductions.",
            "",
        ]
    else:
        lines += [
            f"Your date of joining will be {joining_date}. Your annual compensation",
            f"will be {stipend_or_ctc}, subject to the terms detailed in the",
            "enclosed compensation annexure and applicable statutory deductions.",
            "",
        ]
    lines += [
        f"You will report to {manager} on joining. This offer is contingent upon",
        "verification of your educational credentials, satisfactory background",
        "check, and medical fitness. Please confirm your acceptance by signing",
        "and returning a copy of this letter within 7 days of receipt.",
        "",
        "We look forward to having you on the team.",
        "",
        "Sincerely,",
        f"Human Resources, {company}",
        "",
        f"Acknowledged and accepted: {STUDENT_NAME}, {COLLEGE}, Roll No. {ROLL_NUMBER}",
    ]
    return lines


def ojt_letter(company: str, address: str, role: str, start_date: str, end_date: str,
               manager: str, ref_no: str) -> list[str]:
    return [
        company,
        address,
        "",
        f"Ref: {ref_no}",
        "Date: 30 June 2026",
        "",
        "TO WHOMSOEVER IT MAY CONCERN",
        "",
        f"This is to certify that {STUDENT_NAME} (Roll No. {ROLL_NUMBER}),",
        f"a student of {COLLEGE}, successfully completed On-the-Job Training",
        f"(OJT) with {company} as {role} from {start_date} to {end_date}.",
        "",
        f"During this period, {STUDENT_NAME.split()[0]} worked under the",
        f"guidance of {manager} and was involved in real project assignments,",
        "demonstrating consistent dedication, technical aptitude, and a strong",
        "learning attitude throughout the engagement.",
        "",
        "We found the intern's performance to be satisfactory and wish",
        f"{STUDENT_NAME.split()[0]} success in future endeavours.",
        "",
        "This certificate is issued upon request for academic purposes.",
        "",
        "Sincerely,",
        f"Human Resources, {company}",
    ]


def main() -> None:
    offer_dir = ROOT / "offer-letters"
    ojt_dir = ROOT / "ojt-letters"

    write_pdf(offer_dir / "Google_STEP_Internship_Offer_Letter.pdf", offer_letter(
        company="Google India Private Limited",
        address="Google Building, Embassy GolfLinks Business Park, Bengaluru 560071",
        role="Software Engineering Intern (STEP Program)",
        location="Bengaluru",
        stipend_or_ctc="INR 1,10,000",
        joining_date="12 January 2027",
        manager="Ananya Krishnan, Engineering Manager",
        ref_no="GOOG-STEP-2026-8841",
        duration="10 weeks",
    ))

    write_pdf(offer_dir / "JPMorganChase_SummerAnalyst_Offer_Letter.pdf", offer_letter(
        company="JPMorgan Chase & Co.",
        address="J.P. Morgan Tower, Kalina, Santacruz East, Mumbai 400098",
        role="Summer Analyst - Technology",
        location="Mumbai",
        stipend_or_ctc="INR 75,000",
        joining_date="05 May 2027",
        manager="Rajeev Menon, Vice President, Technology",
        ref_no="JPMC-SA-2026-3327",
        duration="8 weeks",
    ))

    write_pdf(offer_dir / "MorganStanley_TechnologyAnalyst_Offer_Letter.pdf", offer_letter(
        company="Morgan Stanley Advantage Services Pvt. Ltd.",
        address="One International Center, Senapati Bapat Marg, Mumbai 400013",
        role="Technology Analyst",
        location="Mumbai",
        stipend_or_ctc="INR 12,50,000 per annum",
        joining_date="03 August 2027",
        manager="Sneha Kulkarni, Associate Director, Technology",
        ref_no="MS-TA-2026-5510",
    ))

    write_pdf(offer_dir / "UBS_GraduateTalentProgram_Offer_Letter.pdf", offer_letter(
        company="UBS Business Solutions (India) Pvt. Ltd.",
        address="UBS House, 2/F, Godrej BKC, Bandra Kurla Complex, Mumbai 400051",
        role="Graduate Talent Program - Technology",
        location="Pune",
        stipend_or_ctc="INR 11,80,000 per annum",
        joining_date="14 July 2027",
        manager="Alok Bhattacharya, Director, Group Technology",
        ref_no="UBS-GTP-2026-1179",
    ))

    write_pdf(offer_dir / "ZS_Associates_BTAssociate_Offer_Letter.pdf", offer_letter(
        company="ZS Associates India Pvt. Ltd.",
        address="World Trade Center, Kharadi, Pune 411014",
        role="Business Technology Solutions Associate",
        location="Pune",
        stipend_or_ctc="INR 9,60,000 per annum",
        joining_date="21 June 2027",
        manager="Meera Iyer, Manager, Technology",
        ref_no="ZS-BTA-2026-6602",
    ))

    write_pdf(ojt_dir / "JPMorganChase_OJT_Completion_Certificate.pdf", ojt_letter(
        company="JPMorgan Chase & Co.",
        address="J.P. Morgan Tower, Kalina, Santacruz East, Mumbai 400098",
        role="Technology Intern",
        start_date="01 December 2026",
        end_date="28 February 2027",
        manager="Rajeev Menon, Vice President, Technology",
        ref_no="JPMC-OJT-2026-9012",
    ))

    write_pdf(ojt_dir / "Google_OJT_Completion_Letter.pdf", ojt_letter(
        company="Google India Private Limited",
        address="Google Building, Embassy GolfLinks Business Park, Bengaluru 560071",
        role="Software Engineering OJT Trainee",
        start_date="01 December 2026",
        end_date="28 February 2027",
        manager="Ananya Krishnan, Engineering Manager",
        ref_no="GOOG-OJT-2026-4471",
    ))

    write_pdf(ojt_dir / "MorganStanley_OJT_Completion_Letter.pdf", ojt_letter(
        company="Morgan Stanley Advantage Services Pvt. Ltd.",
        address="One International Center, Senapati Bapat Marg, Mumbai 400013",
        role="Technology OJT Trainee",
        start_date="01 December 2026",
        end_date="28 February 2027",
        manager="Sneha Kulkarni, Associate Director, Technology",
        ref_no="MS-OJT-2026-7734",
    ))

    print("Repository samples written under", ROOT)


if __name__ == "__main__":
    main()
