#!/usr/bin/env python3
"""Audit compulsory source for demo data, browser storage, and dead actions.

The audit intentionally stays dependency-free so it can run before the
backend/frontend environments are installed:

    python qa/audit_p0.py

Findings are printed with source locations.  Only ``P0`` findings make the
process fail; advisory findings (for example a timeout used only to dismiss a
toast) are reported without failing CI.  Deferred USP files and test/fixture
trees are not part of the compulsory scan.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_ROOTS = (
    "frontend/src",
    "backend/app",
    "services/api/app",
    "apps/web/src",
    "apps/api/app",
)
SOURCE_SUFFIXES = {".js", ".jsx", ".ts", ".tsx", ".py", ".vue", ".svelte"}

TEST_PARTS = {
    "test",
    "tests",
    "__tests__",
    "fixtures",
    "fixture",
    "test_fixtures",
}

# The product specification identifies these as P1/P2 or deferred USP work;
# their mock/demo scaffolds should not obscure P0 findings while those flows
# are intentionally unfinished.
DEFERRED_FILE_NAMES = {
    "reconstructmyyear.jsx",
    "anyformassistant.jsx",
    "deadlinerescue.jsx",
    "evidenceautopilot.jsx",
    "teachingchangedetector.jsx",
    "promotiondossier.jsx",
    "nextbestmove.jsx",
    "lorstudio.jsx",
    "cvimport.jsx",
}
DEFERRED_MARKERS = (
    "/reconstruct/",
    "/any-form/",
    "/deadline-rescue/",
    "/evidence-autopilot/",
    "/teaching-change/",
    "/promotion-dossier/",
    "/next-best-move/",
    "/lor-studio/",
    "/cv-import/",
)


@dataclass(frozen=True)
class Rule:
    category: str
    pattern: re.Pattern[str]
    severity: str = "P0"
    explanation: str = ""


@dataclass(frozen=True)
class Finding:
    severity: str
    category: str
    path: Path
    line_number: int
    line: str
    explanation: str


def _rule(category: str, pattern: str, explanation: str, severity: str = "P0") -> Rule:
    return Rule(category, re.compile(pattern, re.IGNORECASE), severity, explanation)


RULES = (
    _rule(
        "mock import",
        r"\b(?:from|import)\b[^\n;]*(?:mock[_-]?data|mock(?:s)?|fake[_-]?data|faker)\b",
        "P0 source must read from the API/database, not mock data.",
    ),
    _rule(
        "known demo identity",
        r"\b(?:dr\.?\s+ananya\s+sharma|dr\.?\s+rajesh\s+(?:iyer|kumar)|dr\.?\s+meera\s+kulkarni|dr\.?\s+k\.?\s*v\.?\s*r\.?\s*murthy|ananya\.sharma@|rajesh\.iyer@|meera\.kulkarni@|dean\.academics@|westfield\s+university)\b",
        "known demo identities must not be hardcoded into compulsory product paths.",
    ),
    _rule(
        "known demo metric",
        r"\b(?:1\.8m\+|92%|72%|82%|12\s*/\s*16|48\s*/\s*67|40\+\s+(?:confirmed\s+)?activities|15\s+evidence|6\s+pending\s+publication|12\s+submissions|24\s+faculty|(?:120|89|56|74|33|41)\s+(?:activities|items))\b",
        "visible P0 metrics must come from persisted data.",
    ),
    _rule(
        "browser storage",
        r"\b(?:localStorage|sessionStorage|indexedDB)\b",
        "personal/application state must use the authenticated API contract; browser storage is not allowed in P0.",
    ),
    _rule(
        "Date.now identifier",
        r"\b(?:id|key|uuid)\s*:\s*Date\.now\s*\(",
        "record identifiers must be generated by the backend/database.",
    ),
    _rule(
        "dead alert handler",
        r"\balert\s*\(",
        "alerts are not a functioning P0 action or error state.",
    ),
    _rule(
        "dead click handler",
        r"\bonClick\s*=\s*\{\s*(?:\(\s*\)\s*=>\s*\{\s*\}|console\.log\b|undefined\b)",
        "every visible P0 control needs a real mutation/navigation handler.",
    ),
    _rule(
        "empty handler",
        r"\b(?:const|let|function)\s+handle[A-Za-z0-9_]*\s*(?:=\s*)?\([^)]*\)\s*(?:=>\s*)?\{\s*\}",
        "empty handlers are dead buttons.",
    ),
)


def _is_test_or_fixture(path: Path) -> bool:
    name = path.name.lower()
    return (
        any(part.lower() in TEST_PARTS for part in path.parts)
        or "fixture" in name
        or name.endswith((".test.js", ".test.jsx", ".test.ts", ".test.tsx", ".spec.js", ".spec.ts"))
    )


def _is_deferred(path: Path) -> bool:
    lowered = "/" + "/".join(part.lower() for part in path.parts) + "/"
    if path.name.lower() in DEFERRED_FILE_NAMES:
        return True
    return any(marker in lowered for marker in DEFERRED_MARKERS)


def _source_files(source_roots: Iterable[Path]) -> Iterable[Path]:
    seen: set[Path] = set()
    for root in source_roots:
        if not root.exists():
            continue
        if root.is_file():
            candidates = (root,)
        else:
            candidates = root.rglob("*")
        for path in candidates:
            if not path.is_file() or path.suffix.lower() not in SOURCE_SUFFIXES:
                continue
            resolved = path.resolve()
            if resolved in seen or _is_test_or_fixture(path) or _is_deferred(path):
                continue
            seen.add(resolved)
            yield path


def _set_timeout_rule(line: str, context: str = "") -> Rule | None:
    if not re.search(r"\bsetTimeout\s*\(", line, re.IGNORECASE):
        return None
    simulation_markers = (
        "loading",
        "simulate",
        "fake",
        "demo",
        "login",
        "signin",
        "sign_in",
        "setisloading",
        "setselectedssoaccount",
        "setcurrentrole",
    )
    haystack = f"{line}\n{context}".lower()
    if any(marker in haystack for marker in simulation_markers):
        return _rule(
            "setTimeout simulation",
            r"\bsetTimeout\s*\(",
            "P0 flows must await a real API/job, not simulate completion with a timer.",
        )
    return _rule(
        "setTimeout",
        r"\bsetTimeout\s*\(",
        "review timer use; UI cleanup timers are advisory, API/job simulation is compulsory.",
        severity="WARN",
    )


def audit(paths: Iterable[Path]) -> list[Finding]:
    findings: list[Finding] = []
    seen: set[tuple[str, str, int, str]] = set()
    for path in _source_files(paths):
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeDecodeError) as exc:
            findings.append(
                Finding(
                    "WARN",
                    "unreadable source",
                    path,
                    0,
                    "",
                    str(exc),
                )
            )
            continue
        for line_number, line in enumerate(lines, start=1):
            context = "\n".join(
                lines[max(0, line_number - 3) : min(len(lines), line_number + 2)]
            )
            rules = (*RULES, _set_timeout_rule(line, context))
            for rule in rules:
                if rule is None or not rule.pattern.search(line):
                    continue
                key = (str(path), rule.category, line_number, line.strip())
                if key in seen:
                    continue
                seen.add(key)
                findings.append(
                    Finding(
                        rule.severity,
                        rule.category,
                        path,
                        line_number,
                        line.strip(),
                        rule.explanation,
                    )
                )
    return findings


def _display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-root",
        action="append",
        dest="source_roots",
        help="source root to scan (repeatable; defaults to known P0 layouts)",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    roots = tuple(
        (REPO_ROOT / root if not Path(root).is_absolute() else Path(root))
        for root in (args.source_roots or DEFAULT_SOURCE_ROOTS)
    )
    findings = audit(roots)
    if not findings:
        print("P0 audit: clean (no findings)")
        return 0

    for finding in findings:
        location = f"{_display_path(finding.path)}:{finding.line_number}"
        print(f"[{finding.severity}] {finding.category} {location}")
        if finding.line:
            print(f"  {finding.line}")
        print(f"  {finding.explanation}")

    compulsory = sum(finding.severity == "P0" for finding in findings)
    warnings = sum(finding.severity == "WARN" for finding in findings)
    print(f"P0 audit: {compulsory} compulsory finding(s), {warnings} warning(s)")
    return 1 if compulsory else 0


if __name__ == "__main__":
    sys.exit(main())
